# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
defaults: &defaults
  working_directory: /go/src/github.com/stairlin/kargo
  docker:
    - image: circleci/golang:1.9

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make test

  release:
    <<: *defaults
    steps:
      - checkout
      - run: ./.circleci/install_goreleaser.sh
      - run:
          name: Build & Publish release
          command: ./goreleaser || true

workflows:
  version: 2
  build-test-and-release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
